version: '3.10'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/fabric
      - ./data/db:/fabric/db
    command: ["./start.sh"]
