# Generated by Django 4.2.5 on 2023-10-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_newsletter_client_operator_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='client_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
