# Generated by Django 4.2.5 on 2023-10-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_newsletter_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='creation_datetime',
            new_name='created_datetime',
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
