# Generated by Django 4.2.5 on 2023-10-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_rename_creation_datetime_message_created_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('total_messages_sent', models.IntegerField(default=0)),
            ],
        ),
    ]
