# Generated by Django 4.2.5 on 2023-10-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_newsletterstatistics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterStatistics',
            new_name='StatisticsNewletter',
        ),
    ]
